import { afterEach, describe, expect, it } from 'vitest';
import { mkdtemp, readFile, rm } from 'node:fs/promises'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
import { MockResolver, PlaymogoResolver, QueueWorker, Store, validatePublicUrl, type Resolver } from '../src/index.js';
const dirs:string[]=[]; async function setup(){const dir=await mkdtemp(join(tmpdir(),'lustre-'));dirs.push(dir);return {dir,store:new Store(join(dir,'queue.db'))};} afterEach(async()=>{await Promise.all(dirs.splice(0).map(d=>rm(d,{recursive:true,force:true})));});
describe('queue persistence and safety',()=>{
 it('recovers an in-progress job after restart',async()=>{const {store}=await setup(),j=store.add('https://example.com/page');expect(store.claim()!.state).toBe('running');store.recover();expect(store.get(j.id)!.state).toBe('queued');});
 it('rejects local-network submission URLs',()=>{expect(()=>validatePublicUrl('http://127.0.0.1/x')).toThrow(/Private/);expect(()=>validatePublicUrl('file:///tmp/a')).toThrow();});
 it('re-extracts primary URL each time a job starts',async()=>{const {store,dir}=await setup();const j=store.add('https://example.com/page');let calls=0;const resolver:Resolver={name:'test',resolve:async url=>{calls++;expect(url).toBe(j.pageUrl);return [{url:'https://cdn.example/file.mp4',headers:{},provider:'test'}]}};const worker=new QueueWorker(store,[resolver],dir,1,async()=>new Response(new Uint8Array(2048),{headers:{'content-type':'video/mp4'}}));worker.start();await new Promise(r=>setTimeout(r,650));worker.stop();expect(calls).toBe(1);expect(store.get(j.id)!.state).toBe('completed');});
 it('rejects HTML error bodies before completion',async()=>{const {store,dir}=await setup();store.add('https://example.com/page');const w=new QueueWorker(store,[new MockResolver()],dir,1,async()=>new Response('<html>denied</html>',{headers:{'content-type':'text/html'}}));w.start();await new Promise(r=>setTimeout(r,650));w.stop();expect(store.list()[0].state).toBe('failed');expect(store.list()[0].error).toMatch(/Rejected/);});
 it('propagates required source headers to direct transfers',async()=>{const {store,dir}=await setup();store.add('https://example.com/page');let received:Headers|undefined;const resolver:Resolver={name:'headers',resolve:async()=>[{url:'https://cdn.example/file',headers:{Referer:'https://example.com/page','User-Agent':'agent',Accept:'*/*','Accept-Language':'en-US',Range:'bytes=0-'},provider:'headers'}]};const w=new QueueWorker(store,[resolver],dir,1,async(_url,init)=>{received=new Headers(init!.headers);return new Response(new Uint8Array(2048),{headers:{'content-type':'video/mp4'}})});w.start();await new Promise(r=>setTimeout(r,650));w.stop();expect(received!.get('range')).toBe('bytes=0-');expect(received!.get('referer')).toBe('https://example.com/page');});
 it('keeps resolving after a static provider failure so browser fallback can run',async()=>{const {store,dir}=await setup();store.add('https://example.com/page');const fallback:Resolver={name:'playwright-media-capture',resolve:async()=>[{url:'https://cdn.example/file.mp4',headers:{},provider:'browser'}]};const w=new QueueWorker(store,[{name:'static',resolve:async()=>{throw new Error('challenge')}},fallback],dir,1,async()=>new Response(new Uint8Array(2048),{headers:{'content-type':'video/mp4'}}));w.start();await new Promise(r=>setTimeout(r,650));w.stop();expect(store.list()[0].state).toBe('completed');expect(store.traces(store.list()[0].id).some(t=>t.stage==='resolver-failed')).toBe(true);});
 it('uses the Playmogo pass_md5 flow for a Dood landing page',async()=>{const calls:{url:string,headers:Headers}[]=[];const fetcher:any=async(url:any,init:any)=>{calls.push({url:String(url),headers:new Headers(init?.headers)});if(String(url).includes('/d/'))return new Response('<iframe src="/e/player-id"></iframe>');if(String(url).includes('/e/'))return new Response("$.get('/pass_md5/test/hash', function(data){}); function x(){return a+'?token=token-value&expiry='+Date.now()} ");return new Response('https://edge.cloudatacdn.com/media~')};const result=await new PlaymogoResolver(fetcher).resolve('https://playmogo.com/d/landing-id');expect(result).toHaveLength(1);expect(result[0].url).toMatch(/^https:\/\/edge\.cloudatacdn\.com\/media~[A-Za-z0-9]{10}\?token=token-value&expiry=\d+$/);expect(result[0].headers.Referer).toBe('https://playmogo.com/e/player-id');expect(calls[2].headers.get('x-requested-with')).toBe('XMLHttpRequest');});
});
