let active,listenerError='';
const media=url=>/(cloudatacdn|mxcontent|\.m3u8|\.mp4)(?:\?|$)/i.test(url);
const allowed=new Set(['referer','user-agent','accept','accept-language','range','cookie']);
const providerUrls=['<all_urls>'];
const status=message=>chrome.storage.local.set({verificationStatus:message});
async function start(message){try{if(listenerError)throw new Error(listenerError);const config=await chrome.storage.local.get(['apiUrl','token']);if(!config.apiUrl||!config.token){await chrome.runtime.openOptionsPage();throw new Error('Configure the LustreStudio Chrome extension, then submit again.')}active={jobId:message.jobId,pageUrl:message.pageUrl,apiUrl:config.apiUrl.replace(/\/$/,''),token:config.token,headers:new Map};const tab=await chrome.tabs.create({url:message.pageUrl,active:true});active.tabId=tab.id;status('Chrome opened the provider page. Complete verification and start playback.')}catch(error){console.error('LustreStudio startup failed',error);status(`Extension startup failed: ${error instanceof Error?error.message:String(error)}`)}}
chrome.storage.onChanged.addListener((changes,area)=>{const pending=changes.pendingVerification?.newValue;if(area==='local'&&pending)void start(pending)});
async function handoff(details,headers){const current=active;if(!current||details.tabId!==current.tabId||!media(details.url))return;active=undefined;try{status('Media request captured. Starting seedbox download…');const cookies=[...(await chrome.cookies.getAll({url:current.pageUrl})),...(await chrome.cookies.getAll({url:details.url}))],cookie=[...new Map(cookies.map(c=>[`${c.domain}:${c.path}:${c.name}`,`${c.name}=${c.value}`])).values()].join('; ');if(cookie)headers.Cookie=cookie;if(!headers.Referer)headers.Referer=current.pageUrl;const response=await fetch(`${current.apiUrl}/api/jobs/${current.jobId}/verified-source`,{method:'POST',headers:{Authorization:`Bearer ${current.token}`,'content-type':'application/json'},body:JSON.stringify({source:{url:details.url,headers}})});if(!response.ok)throw new Error('Seedbox rejected the handoff');status('Seedbox download started.');await chrome.tabs.remove(details.tabId)}catch(error){console.error('LustreStudio handoff failed',error);status(`Media handoff failed: ${error instanceof Error?error.message:String(error)}`)}}
try{chrome.webRequest.onBeforeSendHeaders.addListener(details=>{if(!active||details.tabId!==active.tabId||!media(details.url))return;const headers=Object.fromEntries((details.requestHeaders||[]).filter(header=>allowed.has(header.name.toLowerCase())&&header.value).map(header=>[header.name,header.value]));void handoff(details,headers)},{urls:providerUrls},['requestHeaders','extraHeaders'])}catch(error){listenerError=error instanceof Error?error.message:String(error);console.error('LustreStudio listener setup failed',listenerError)}
