// @ts-nocheck
import { createServer } from 'node:http';
import { appendFileSync, chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { createInterface } from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import { chromium } from 'playwright';

const root=join(homedir(),'.config','lustrestudio-verifier'), configPath=join(root,'config.json'), keychainService='LustreStudioServerToken';
const log=(message:string)=>appendFileSync(join(root,'helper.log'),`${new Date().toISOString()} ${message}\n`);
type Config={apiUrl:string};
const readConfig=()=>JSON.parse(readFileSync(configPath,'utf8')) as Config;
const token=()=>{const result=spawnSync('security',['find-generic-password','-w','-a',process.env.USER||'', '-s',keychainService],{encoding:'utf8'});if(result.status!==0)throw new Error('LustreStudio token is not configured');return result.stdout.trim()};
async function install(){if(process.platform!=='darwin')throw new Error('The local verifier is macOS-only');const prompt=createInterface({input:stdin,output:stdout});const apiUrl=(await prompt.question('LustreStudio server URL: ')).replace(/\/$/,'');const value=await prompt.question('API token: ');prompt.close();if(!/^https:\/\//.test(apiUrl)||!value)throw new Error('A HTTPS server URL and token are required');mkdirSync(root,{recursive:true});writeFileSync(configPath,JSON.stringify({apiUrl}));chmodSync(configPath,0o600);const saved=spawnSync('security',['add-generic-password','-U','-a',process.env.USER||'', '-s',keychainService,'-w',value],{encoding:'utf8'});if(saved.status!==0)throw new Error(saved.stderr.trim()||'Could not save token in Keychain');const agent=join(homedir(),'Library','LaunchAgents','com.lustrestudio.local-verifier.plist'),script=fileURLToPath(import.meta.url),tsx=resolve(import.meta.dirname,'../../../node_modules/tsx/dist/cli.mjs'),plist=`<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>Label</key><string>com.lustrestudio.local-verifier</string><key>ProgramArguments</key><array><string>${process.execPath}</string><string>${tsx}</string><string>${script}</string></array><key>RunAtLoad</key><true/><key>KeepAlive</key><true/></dict></plist>`;writeFileSync(agent,plist);const domain=`gui/${process.getuid?.()||0}`;spawnSync('launchctl',['bootout',domain,agent]);const started=spawnSync('launchctl',['bootstrap',domain,agent],{encoding:'utf8'});if(started.status!==0)throw new Error(started.stderr.trim()||'Could not start local verifier');console.log('LustreStudio local verifier installed and running.');}
const active=new Set<string>();
function choosePage(context:any){return context.pages().find((page:any)=>page.url()!=='about:blank')??context.pages()[0]??null}
async function verify(jobId:string){if(active.has(jobId))return;active.add(jobId);let context:any;try{const config=readConfig(), auth=token(), get=async(path:string)=>{const response=await fetch(config.apiUrl+path,{headers:{Authorization:`Bearer ${auth}`}});if(!response.ok)throw new Error(`Server rejected local verifier request (${response.status})`);return response.json()};const job=await get(`/api/jobs/${jobId}`);context=await chromium.launchPersistentContext(join(root,'chrome-profile'),{channel:'chrome',headless:false,locale:'en-US'});const page=choosePage(context)??await context.newPage();await page.bringToFront();const sources=new Map<string,string>();page.on('response',(response:any)=>{const url=response.url(),type=response.headers()['content-type']||'';if(/video|audio|application\/vnd\.apple\.mpegurl/i.test(type)||/(cloudatacdn|mxcontent|\.m3u8|\.mp4)(?:\?|$)/i.test(url))sources.set(url,page.url())});await page.goto(job.pageUrl,{waitUntil:'domcontentloaded',timeout:45_000});const until=Date.now()+600_000;while(!sources.size&&Date.now()<until)await page.waitForTimeout(500);const captured=sources.entries().next().value;if(!captured)throw new Error('No media request captured within 10 minutes');const [url,referer]=captured,cookies=(await context.cookies()).map(c=>`${c.name}=${c.value}`).join('; ');const response=await fetch(config.apiUrl+`/api/jobs/${jobId}/verified-source`,{method:'POST',headers:{Authorization:`Bearer ${auth}`,'content-type':'application/json'},body:JSON.stringify({source:{url,headers:{Referer:referer,'User-Agent':'Mozilla/5.0','Accept':'*/*','Accept-Language':'en-US,en;q=0.9',...(cookies?{Cookie:cookies}:{})}}})});if(!response.ok)throw new Error(`Server rejected captured media request (${response.status})`);log(`Handoff accepted for ${jobId}`);await context.close();}catch(error){const message=error instanceof Error?error.message:String(error);log(`Verification failed for ${jobId}: ${message}`);console.error(message)}finally{active.delete(jobId)}}
if(process.argv[2]==='install')await install();else createServer((req,res)=>{const jobId=new URL(req.url||'/',`http://${req.headers.host}`).searchParams.get('jobId');if(req.url?.startsWith('/verify')&&jobId&&/^[a-f0-9]{16}$/.test(jobId)){void verify(jobId);res.writeHead(200,{'content-type':'text/html'}).end('<title>LustreStudio</title><p>Opening local Chrome for verification. Complete the normal check and start playback.</p>');}else res.writeHead(404).end()}).listen(8791,'127.0.0.1',()=>console.log('LustreStudio local verifier listening on http://127.0.0.1:8791'));
